/**
 * LiveKit configuration
 * Note: API key and secret should NEVER be in the frontend
 * Tokens are generated by the backend
 */
export const getLiveKitConfig = () => {
  const livekitUrl = process.env.REACT_APP_LIVEKIT_URL;
  const backendUrl =
    process.env.REACT_APP_BACKEND_URL || "http://localhost:5000";

  if (!livekitUrl) {
    throw new Error(
      "LiveKit URL is missing. Please check your REACT_APP_LIVEKIT_URL environment variable."
    );
  }

  return {
    url: livekitUrl,
    backendUrl,
  };
};
